-- Legacy file intentionally left blank.
-- Use:
-- BuildArcadeWorld.server.lua
-- ArcadeLightAnimator.server.lua
-- ClawMachineService.server.lua
-- AvatarCustomizationService.server.lua
-- KamPetService.server.lua
